### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by hovi** [ZdenkaZ/hra#1]
- Take a look at markdown language.
- Create branch "issue-1-readme" and create README.md file.
- Put in basic information about the project, why does it exists, what do you want to do with it.
- Format nicely using the [markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).
- [Link the commit](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to this issue
- Push the branch, create pull request, request review from me.

**Comment by ZdenkaZ** [comment]
This should link the last commit - creating a readme.md file - to this issue: 70a7f74bb9ee6e5b50f8e652ca7ac7c58c11f677

**Comment by ZdenkaZ** [comment]
Clone the repository to a different folder in my pc.
get to the issue branch: C:\Users\Zdenka Herova\Documents\hra>git checkout issue-1-readme
check C:\Users\Zdenka Herova\Documents\hra>git branch - you should be on the issue-1... branch
commit the readme.md file
push the readme.md file

**Comment by ZdenkaZ** [comment]
English version - the one from Thursday got lost in the universe for some mystical reason...

**Comment by ZdenkaZ** [comment]
Linking the commit of bilingual README to this issue: 55473cd4573091948675610050d308f15fb914c6
